// Misc actions.
export const INIT_APPLICATION = 'INIT_APPLICATION';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';

// Session related actions
export const RESTORE_LAST_SESSION = 'RESTORE_LAST_SESSION';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// Drawer related actions.
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

// Forms related actions.
export const INIT_FORM = 'INIT_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const RESET_FORM = 'RESET_FORM';
export const RESET_FORM_FIELD = 'RESET_FORM_FIELD';
export const SET_FORM_VALIDITY = 'SET_FORM_VALIDITY';
export const TOUCH_FORM = 'TOUCH_FORM';
export const DISPOSE_FORM = 'DISPOSE_FORM';

// Modals related actions.
export const OPEN_MODAL = 'OPEN_MODAL';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const REPLACE_MODAL = 'REPLACE_MODAL';
export const LOCK_ACTIVE_MODAL = 'LOCK_ACTIVE_MODAL';
export const CLOSE_ACTIVE_MODAL = 'CLOSE_ACTIVE_MODAL';

// Notifications related actions.
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'; // TODO REMOVE: This is a temp action to support older architecture

// System related actions.
export const START_FETCH_SYSTEM_INFO = 'START_FETCH_SYSTEM_INFO';
export const COMPLETE_FETCH_SYSTEM_INFO = 'COMPLETE_FETCH_SYSTEM_INFO';
export const FAIL_FETCH_SYSTEM_INFO = 'FAIL_FETCH_SYSTEM_INFO';
export const START_UPGRADE_SYSTEM = 'START_UPGRADE_SYSTEM';

// Node installation related actions.
export const START_FETCH_NODE_INSTALLATION_COMMANDS = 'START_FETCH_NODE_INSTALLATION_COMMANDS';
export const COMPLETE_FETCH_NODE_INSTALLATION_COMMANDS = 'COMPLETE_FETCH_NODE_INSTALLATION_COMMANDS';
export const FAIL_START_FETCH_NODE_INSTALLATION_COMMANDS = 'FAIL_START_FETCH_NODE_INSTALLATION_COMMANDS';

// Alerts related actions.
export const START_FETCH_ALERTS = 'START_FETCH_ALERTS';
export const COMPLETE_FETCH_ALERTS = 'COMPLETE_FETCH_ALERTS';
export const FAIL_FETCH_ALERTS = 'FAIL_FETCH_ALERTS';
export const START_UPDATE_ALERTS = 'START_UPDATE_ALERTS';
export const COMPLETE_UPDATE_ALERTS = 'COMPLETE_UPDATE_ALERTS';
export const FAIL_UPDATE_ALERTS = 'FAIL_UPDATE_ALERTS';
export const UPDATE_ALERTS_UNREAD_COUNT = 'UPDATE_ALERTS_UNREAD_COUNT';
export const DROP_ALERTS = 'DROP_ALERTS';

// Account related actions.
export const START_CREATE_ACCOUNT = 'START_CREATE_ACCOUNT';
export const COMPLETE_CREATE_ACCOUNT = 'COMPLETE_CREATE_ACCOUNT';
export const FAIL_CREATE_ACCOUNT = 'FAIL_CREATE_ACCOUNT';
export const START_UPDATE_ACCOUNT_S3_ACCESS = 'START_UPDATE_ACCOUNT_S3_ACCESS';
export const COMPLETE_UPDATE_ACCOUNT_S3_ACCESS = 'COMPLETE_UPDATE_ACCOUNT_S3_ACCESS';
export const FAIL_UPDATE_ACCOUNT_S3_ACCESS_UPDATE = 'FAIL_UPDATE_ACCOUNT_S3_ACCESS_UPDATE';

// Object related actions.
export const START_OBJECT_UPLOAD = 'START_OBJECT_UPLOAD';
export const UPDATE_OBJECT_UPLOAD = 'UPDATE_OBJECT_UPLOAD';
export const COMPLETE_OBJECT_UPLOAD = 'COMPLETE_OBJECT_UPLOAD';
export const FAIL_OBJECT_UPLOAD = 'FAIL_OBJECT_UPLOAD';
export const CLEAR_COMPLETED_OBJECT_UPLOADES = 'CLEAR_COMPLETED_OBJECT_UPLOADES';

