apiVersion: batch/v1
kind: Job
metadata:
  name: TEST_JOB_NAME_PLACEHOLDER
spec:
  template:
    spec:
      serviceAccount: noobaa-tests-account
      containers:
      - name: noobaa-test
        image: TESTER_IMAGE_PLACEHOLDER
        imagePullPolicy: Never
        workingDir: /noobaa-core
        args:          
          - node
          - ./src/test/framework/test_env_builder_kubernetes.js
          - --image
          - NOOBAA_IMAGE_PLACEHOLDER
          - --namespace_prefix 
          - NAMESPACE_PREFIX_PLACEHOLDER
          - --tests_list
          - /noobaa-core/src/test/framework/sanity_tests_list.js
        env:
          - name: CONTAINER_PLATFORM
            value: KUBERNETES
          - name: SUPPRESS_LOGS
            value: "TRUE"
      restartPolicy: Never
  backoffLimit: 0

