@startuml
/'To generate png file, use https://www.plantuml.com/plantuml '/

title Create User Using IAM

actor "client (root user)" as C order 10
participant "IAM Server (endpoint)" as IS order 20
participant "endpoint_request_handler" as ERH order 30
participant "AccountSpace" as ASG order 40
participant "AccountSpaceFS" as ASF order 50
participant "FileSystem" as FS order 60

C ->  IS: CreateUser request
IS ->  ERH: handle_request
ERH -> ASG: create_user
ASG -> ASF: create_user
ASF -> FS: create_config_file
note right: usable after CreateAccessKey
ASF -> ERH: creation_details
ERH -> IS: send_reply
IS -> C: CreateUser reply

@enduml
