language: node_js
node_js:
- "7"
- "6"
- "5"
- "4"

install:
    npm install --global mocha

script:
  - export TEST_MODE=TRAVIS
  - export NS_HOST=$NS_HOST
  - export NS_KEYNAME=$NS_KEYNAME
  - export NS_KEY=$NS_KEY
  - export NS_CPCODE=$NS_CPCODE
  - npm install
  - mocha --no-timeouts test/test-netstorage.js
