apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: backingstore
  labels:
    app: noobaa
  finalizers:
    - noobaa.io/finalizer
spec:
  pvPool:
    secret:
      name: SECRET_NAME
    numVolumes: 3
    resources:
      requests:
        storage: 16Gi
    storageClass: standard
  type: pv-pool
