// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"noobaa-operator/pkg/apis/noobaa/v1alpha1.Noobaa":       schema_pkg_apis_noobaa_v1alpha1_Noobaa(ref),
		"noobaa-operator/pkg/apis/noobaa/v1alpha1.NoobaaSpec":   schema_pkg_apis_noobaa_v1alpha1_NoobaaSpec(ref),
		"noobaa-operator/pkg/apis/noobaa/v1alpha1.NoobaaStatus": schema_pkg_apis_noobaa_v1alpha1_NoobaaStatus(ref),
	}
}

func schema_pkg_apis_noobaa_v1alpha1_Noobaa(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Noobaa is the Schema for the noobaas API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("noobaa-operator/pkg/apis/noobaa/v1alpha1.NoobaaSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("noobaa-operator/pkg/apis/noobaa/v1alpha1.NoobaaStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "noobaa-operator/pkg/apis/noobaa/v1alpha1.NoobaaSpec", "noobaa-operator/pkg/apis/noobaa/v1alpha1.NoobaaStatus"},
	}
}

func schema_pkg_apis_noobaa_v1alpha1_NoobaaSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NoobaaSpec defines the desired state of Noobaa",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_noobaa_v1alpha1_NoobaaStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NoobaaStatus defines the observed state of Noobaa",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
