mkdir  c:\noobaa
cd c:\noobaa
powershell wget https://s3.eu-central-1.amazonaws.com/noobaa-core/noobaa-setup.exe -OutFile noobaa-setup.exe
noobaa-setup.exe /S /config eyJkYmdfbG9nX2xldmVsIjoyLCJ0aWVyIjoibm9kZXMiLCJwcm9kIjp0cnVlLCJidWNrZXQiOiJmaWxlcyIsInJvb3RfcGF0aCI6Ii4vYWdlbnRfc3RvcmFnZS8iLCJhZGRyZXNzIjoid3NzOi8vMjMuMjUxLjEzNS45OTo4NDQzIiwic3lzdGVtIjoiY3RlcmEiLCJhY2Nlc3Nfa2V5IjoiMjM4ZjAzNzg0ZjEwZmJlNzg2OTE3NjAzMTNjNDkzNDEiLCJzZWNyZXRfa2V5IjoiMzVhOTBjNDZlYmU1MDdlODQ3YjU5MzA0ZTVhMjgyOWMyMDk4YWVkOTZhYWIxYTNjNmU3MjA4MjJhMjVmMjk2NCJ9
