<script>
mkdir  c:\noobaa
cd c:\noobaa
powershell wget https://s3.eu-central-1.amazonaws.com/noobaa-core/noobaa-setup.exe -OutFile noobaa-setup.exe
noobaa-setup.exe /S /config ew0KICAgICJkYmdfbG9nX2xldmVsIjogMiwNCiAgICAiYWRkcmVzcyI6ICJ3c3M6Ly81Mi4yOC4xMTAuMTQyIiwNCiAgICAic3lzdGVtIjogImJhbmtwb2FsaW0iLA0KICAgICJ0aWVyIjogIm5vZGVzIiwNCiAgICAicHJvZCI6IHRydWUsDQogICAgImJ1Y2tldCI6ICJmaWxlcyIsDQogICAgInJvb3RfcGF0aCI6ICIuL2FnZW50X3N0b3JhZ2UvIiwNCiAgICAiYWNjZXNzX2tleSI6IjJhNmVhMDg1YjBhMDk3N2E3Y2FhN2E1OWI3N2E2OThkIiwNCiJzZWNyZXRfa2V5IjoiYzhkMWQ5ZjFiMWY0YjUwYzc2MmFlZmIwZDRmOGNjODFjMjM1YTY3YzA0NmYxNmY4MzVlMmUwMTQ3NTA0MWVjMyINCn0=
</script>
