name: Label new PRs

on:
  pull_request:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Add label to new PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Enable-Auto-Rebase']
            })
