name: Build arm64 image
on: [pull_request]

jobs:
  build-arm64-image:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/build-noobaa-image-reusable.yaml
    with:
      container_platform: linux/arm64
      platform_tag_suffix: -linux-arm64
      make_target: noobaa
      enable_binfmt: true
