name: Build ppc64le image
on: [pull_request]

jobs:
  build-ppc64le-image:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/build-noobaa-image-reusable.yaml
    with:
      container_platform: linux/ppc64le
      platform_tag_suffix: -linux-ppc64le
      make_target: noobaa
      enable_binfmt: true
