name: Check Slack Webhook
on: [push, pull_request, workflow_dispatch]


jobs:
  check-slack-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Greetings! (from nbecker)"
