name: Nightly IBM VM Cleanup Dispatcher

on:
    schedule:
        # Run daily at 4 AM UTC (4 hours after the nightly provisioning at midnight)
        - cron: '0 4 * * *'
    workflow_dispatch: # Allow manual triggering for on-demand cleanup

jobs:
  cleanup-warp-vm:
    uses: ./.github/workflows/ibm-nightly-vm-cleanup.yaml
    secrets:
      VM_CONFIG: ${{ secrets.IBM_WARP_VM_CONFIG }}
      IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
