name: Run PR Tests
on: [push, pull_request, workflow_dispatch]
concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
jobs:

  run-sanity-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/sanity.yaml

  run-sanity-ssl-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/sanity-ssl.yaml

  run-unit-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/unit.yaml

  run-unit-tests-postgres:
    needs: build-noobaa-image
    uses: ./.github/workflows/postgres-unit-tests.yaml

  run-nc-unit-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/nc_unit.yml

  ceph-s3-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/ceph-s3-tests.yaml

  ceph-nsfs-s3-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/ceph-nsfs-s3-tests.yaml

  warp-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/warp-tests.yaml

  warp-nc-tests:
    needs: build-noobaa-image
    uses: ./.github/workflows/warp-nc-tests.yaml

  build-noobaa-image:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Quay Registry
        run: |
          docker login quay.io -u ${{ secrets.GHACTIONQUAYNAME }} -p ${{ secrets.GHACTIONQUAYTOKEN }}

      #- name: Pull Base Docker Image from Quay
      #  env:
      #    DOCKERHUB_OWNER: ${{ secrets.GHACTIONQUAYNAME }}
      #  run: |
      #      docker pull quay.io/${{ steps.prep.outputs.basetags }}

      - name: Check changed files
        id: changed_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} > changed_files.txt
          echo "changed_files=$(cat changed_files.txt)" >> $GITHUB_OUTPUT

      - name: make noobaa image
        run: make tester

      - name: create docker artifact
        run: |
          docker save --output noobaa.tar noobaa
          docker save --output noobaa-tester.tar noobaa-tester

      - name: upload noobaa docker image
        uses: actions/upload-artifact@v4
        with:
          name: noobaa-image
          path: noobaa.tar
          retention-days: "1"

      - name: upload noobaa-tester docker image
        uses: actions/upload-artifact@v4
        with:
          name: noobaa-tester
          path: noobaa-tester.tar
          retention-days: "1"
